version: "3.9"
services:
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql  # Data persistence

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  # C Server-Client Pairs
  c_server1:
    build: ./c/server
    container_name: c_server1
    ports:
      - "1025:1025"
    depends_on:
      - mysql

  c_client1:
    build: ./c/client
    container_name: c_client1
    ports:
      - "1026:1026"
    depends_on:
      - c_server1

  c_server2:
    build: ./c/server
    container_name: c_server2
    ports:
      - "1027:1025"  # Adjusted port binding to avoid conflict
    depends_on:
      - mysql

  c_client2:
    build: ./c/client
    container_name: c_client2
    ports:
      - "1028:1026"  # Adjusted port binding to avoid conflict
    depends_on:
      - c_server2

  # Python Server-Client Pairs
  python_server1:
    build: ./phyton/server
    container_name: python_server1
    ports:
      - "1031:1027"  # Adjusted port binding to avoid conflict
    depends_on:
      - mysql

  python_client1:
    build: ./phyton/client
    container_name: python_client1
    ports:
      - "1032:1028"  # Adjusted port binding to avoid conflict
    depends_on:
      - python_server1

  python_server2:
    build: ./phyton/server
    container_name: python_server2
    ports:
      - "1033:1027"  # Adjusted port binding to avoid conflict
    depends_on:
      - mysql

  python_client2:
    build: ./phyton/client
    container_name: python_client2
    ports:
      - "1034:1028"  # Adjusted port binding to avoid conflict
    depends_on:
      - python_server2

  # Additional C Server-Client Pair 1
  c_server3:
    build: ./c/server
    container_name: c_server3
    ports:
      - "1035:1025"  # Adjusted port binding to avoid conflict
    depends_on:
      - mysql

  c_client3:
    build: ./c/client
    container_name: c_client3
    ports:
      - "1036:1026"  # Adjusted port binding to avoid conflict
    depends_on:
      - c_server3

  # Additional Python Server-Client Pair 1
  python_server3:
    build: ./phyton/server
    container_name: python_server3
    ports:
      - "1037:1027"  # Adjusted port binding to avoid conflict
    depends_on:
      - mysql

  python_client3:
    build: ./phyton/client
    container_name: python_client3
    ports:
      - "1038:1028"  # Adjusted port binding to avoid conflict
    depends_on:
      - python_server3

volumes:
  mysql-data:
